---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.vercel.com/v1/integrations/deploy/prj_NgXBLv4o8X0LOvFkUFQfLdMWNcMu/w1NOTAjmVg?buildCache=false
sections:
- type: directory
  path: blog
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: authors
  label: Authors
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
